dist: xenial

language: python

python:
  - '3.8'
  
services:
  - docker

before_install:
- docker pull wnt3rmute/ardupilot-sitl

branches:
  only:
    - master
    - release
    - branch_checker

install:
  - pip install -r requirements.txt


script: pytest -k "_test" # && flake8
